<?php

namespace Database\Seeders;

use App\Models\Item;
use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;

class ItemSeeder extends Seeder
{
  /**
   * Run the database seeds.
   */
  public function run(): void
  {
    $dataItem = [
      [
        'name' => 'Tas (17 x 13 cm)',
        'slug' => str()->slug('27-tas (17 x 13 cm'),
        'price' => 173250,
        'real_price' => 165000,
        'image' => 'item/Tas (17 x 13 cm).jpg',
        'category_id' => 2,
        'seller_id' => 1,
      ],
      [
        'name' => 'Tas (18 x 12 cm)',
        'slug' => str()->slug('27-tas (18 x 12 cm)'),
        'price' => 194250,
        'real_price' => 185000,
        'image' => 'item/gambar-item-20240729225920.jpg',
        'category_id' => 2,
        'seller_id' => 1,
      ],
      [
        'name' => 'Tas (13 x 17 cm)',
        'slug' => str()->slug('27-tas (13 x 17 cm)'),
        'price' => 173250,
        'real_price' => 165000,
        'image' => 'item/Tas (13 x 17 cm).jpg',
        'category_id' => 2,
        'seller_id' => 1,
      ],
      [
        'name' => 'Tas (19 x 13 cm)',
        'slug' => str()->slug('27-tas (19 x 13 cm)'),
        'price' => 262500,
        'real_price' => 250000,
        'image' => 'item/Tas (19 x 13 cm).jpg',
        'category_id' => 2,
        'seller_id' => 1,
      ],
      [
        'name' => 'Tas (11 x 17 cm)',
        'slug' => str()->slug('27-tas (11 x 17 cm'),
        'price' => 131250,
        'real_price' => 125000,
        'image' => 'item/Tas (11 x 17 cm).jpg',
        'category_id' => 2,
        'seller_id' => 1,
      ],
      [
        'name' => 'Tas (17 x 13 cm (mix manik))',
        'slug' => str()->slug('27-tas (17 x 13 cm (mix manik)'),
        'price' => 178500,
        'real_price' => 170000,
        'image' => 'item/Tas (17 x 13 cm (mix manik)).jpg',
        'category_id' => 2,
        'seller_id' => 1,
      ],
      [
        'name' => 'Tas (13 x 19 cm)',
        'slug' => str()->slug('27-tas (13 x 19 cm)'),
        'price' => 183750,
        'real_price' => 175000,
        'image' => 'item/Tas (13 x 19 cm).jpg',
        'category_id' => 2,
        'seller_id' => 1,
      ],
      [
        'name' => 'Tas (13 x 12 cm)',
        'slug' => str()->slug('27-tas (13 x 12 cm)'),
        'price' => 147000,
        'real_price' => 140000,
        'image' => 'item/Tas (13 x 12 cm).jpg',
        'category_id' => 2,
        'seller_id' => 1,
      ],
      [
        'name' => 'Id Card',
        'slug' => str()->slug('27-id card'),
        'price' => 52500,
        'real_price' => 50000,
        'image' => 'item/Id Card.jpg',
        'category_id' => 2,
        'seller_id' => 1,
      ],
      [
        'name' => 'Card Holder',
        'slug' => str()->slug('27-card holder'),
        'price' => 52500,
        'real_price' => 50000,
        'image' => 'item/Card Holder.jpg',
        'category_id' => 2,
        'seller_id' => 1,
      ],
      [
        'name' => '3row Bead',
        'slug' => str()->slug('28-3row bead'),
        'price' => 28350,
        'real_price' => 27000,
        'image' => 'item/3row Bead Bracelet.jpg',
        'category_id' => 2,
        'seller_id' => 2,
      ],
      [
        'name' => '5row Bead Bracelet',
        'slug' => str()->slug('28-5row bead bracelet'),
        'price' => 26250,
        'real_price' => 25000,
        'image' => 'item/5row Bead Bracelet.jpg',
        'category_id' => 2,
        'seller_id' => 2,
      ],
      [
        'name' => 'Kukie Bracelet',
        'slug' => str()->slug('28-kukie bracelet'),
        'price' => 36750,
        'real_price' => 35000,
        'image' => 'item/Kukie-Bracelet.jpg',
        'category_id' => 2,
        'seller_id' => 2,
      ],
      [
        'name' => 'Line Bracelet',
        'slug' => str()->slug('28-line bracelet'),
        'price' => 25200,
        'real_price' => 24000,
        'image' => 'item/Line Bracelet.jpg',
        'category_id' => 2,
        'seller_id' => 2,
      ],
      [
        'name' => 'Paracord Bracelet',
        'slug' => str()->slug('28-paracord bracelet'),
        'price' => 26250,
        'real_price' => 25000,
        'image' => 'item/Paracord Bracelet.jpg',
        'category_id' => 2,
        'seller_id' => 2,
      ],
      [
        'name' => 'Tenun Mekongga',
        'slug' => str()->slug('29-tenun mekongga'),
        'price' => 367500,
        'real_price' => 350000,
        'image' => 'item/Tenun Mekongga.jpg',
        'category_id' => 2,
        'seller_id' => 3,
      ],
      [
        'name' => 'Tenun Tolaki',
        'slug' => str()->slug('29-tenun tolaki'),
        'price' => 157500,
        'real_price' => 150000,
        'image' => 'item/Tenun Tolaki.jpg',
        'category_id' => 2,
        'seller_id' => 3,
      ],
      [
        'name' => 'Tenun Tabere',
        'slug' => str()->slug('29-tenun tabere'),
        'price' => 262500,
        'real_price' => 250000,
        'image' => 'item/Tenun Tabere.jpg',
        'category_id' => 2,
        'seller_id' => 3,
      ],
      [
        'name' => 'Tenun Sangia',
        'slug' => str()->slug('29-tenun sangia'),
        'price' => 525000,
        'real_price' => 500000,
        'image' => 'item/Tenun Sangia.jpeg',
        'category_id' => 2,
        'seller_id' => 3,
      ],
      [
        'name' => 'Tutup Gelas',
        'slug' => str()->slug('29-tutup gelas'),
        'price' => 52500,
        'real_price' => 50000,
        'image' => 'item/Tutup Gelas.jpg',
        'category_id' => 2,
        'seller_id' => 3,
      ],
      [
        'name' => 'Kotak Cendra Mata',
        'slug' => str()->slug('29-kotak cendra mata'),
        'price' => 52500,
        'real_price' => 50000,
        'image' => 'item/Kotak Cendra Mata.jpg',
        'category_id' => 2,
        'seller_id' => 3,
      ],
      [
        'name' => 'Songket Kepala',
        'slug' => str()->slug('29-songket kepala'),
        'price' => 52500,
        'real_price' => 50000,
        'image' => 'item/Songket Kepala.jpg',
        'category_id' => 2,
        'seller_id' => 3,
      ],
      [
        'name' => 'Tas',
        'slug' => str()->slug('29-tas'),
        'price' => 52500,
        'real_price' => 50000,
        'image' => 'item/Tas.jpg',
        'category_id' => 2,
        'seller_id' => 3,
      ],
      [
        'name' => 'Cincin Black Series',
        'slug' => str()->slug('30-cincin black series'),
        'price' => 10500,
        'real_price' => 10000,
        'image' => 'item/Cincin Black Series.jpg',
        'category_id' => 2,
        'seller_id' => 4,
      ],
      [
        'name' => 'Cincin Blue Series',
        'slug' => str()->slug('30-cincin blue series'),
        'price' => 10500,
        'real_price' => 10000,
        'image' => 'item/Cincin Blue Series.jpg',
        'category_id' => 2,
        'seller_id' => 4,
      ],
      [
        'name' => 'Cincin Sun Flower',
        'slug' => str()->slug('30-cincin sun flower'),
        'price' => 10500,
        'real_price' => 10000,
        'image' => 'item/Cincin Sun Flower.jpg',
        'category_id' => 2,
        'seller_id' => 4,
      ],
      [
        'name' => 'Cincin Lotsu',
        'slug' => str()->slug('30-cincin lotsu'),
        'price' => 10500,
        'real_price' => 10000,
        'image' => 'item/Cincin Lotsu.jpg',
        'category_id' => 2,
        'seller_id' => 4,
      ],
      [
        'name' => 'Cincin Green Yellow',
        'slug' => str()->slug('30-cincin green yellow'),
        'price' => 10500,
        'real_price' => 10000,
        'image' => 'item/Cincin Green Yellow.jpg',
        'category_id' => 2,
        'seller_id' => 4,
      ],
      [
        'name' => 'Cincin Love',
        'slug' => str()->slug('30-cincin love'),
        'price' => 10500,
        'real_price' => 10000,
        'image' => 'item/Cincin Love.jpg',
        'category_id' => 2,
        'seller_id' => 4,
      ],
      [
        'name' => 'Cincin Silver',
        'slug' => str()->slug('30-cincin silver'),
        'price' => 10500,
        'real_price' => 10000,
        'image' => 'item/Cincin Silver.jpg',
        'category_id' => 2,
        'seller_id' => 4,
      ],
      [
        'name' => 'Gelang Pink Series',
        'slug' => str()->slug('30-gelang pink series'),
        'price' => 15750,
        'real_price' => 15000,
        'image' => 'item/Gelang Pink Series.jpg',
        'category_id' => 2,
        'seller_id' => 4,
      ],
      [
        'name' => 'Gelang Tali',
        'slug' => str()->slug('30-gelang tali'),
        'price' => 15750,
        'real_price' => 15000,
        'image' => 'item/Gelang Tali.jpg',
        'category_id' => 2,
        'seller_id' => 4,
      ],
      [
        'name' => 'Gelang Tali Huruf',
        'slug' => str()->slug('30-gelang tali huruf'),
        'price' => 21000,
        'real_price' => 20000,
        'image' => 'item/Gelang Tali Huruf.jpg',
        'category_id' => 2,
        'seller_id' => 4,
      ],
      [
        'name' => 'Gelang Mutiara Putih',
        'slug' => str()->slug('30-gelang mutiara putih'),
        'price' => 21000,
        'real_price' => 20000,
        'image' => 'item/Gelang Mutiara Putih.jpg',
        'category_id' => 2,
        'seller_id' => 4,
      ],
      [
        'name' => 'Gantungan HP',
        'slug' => str()->slug('30-gantungan hp'),
        'price' => 31500,
        'real_price' => 30000,
        'image' => 'item/Gantungan HP.jpg',
        'category_id' => 2,
        'seller_id' => 4,
      ],
      [
        'name' => 'Arumi Ring',
        'slug' => str()->slug('31-arumi ring'),
        'price' => 6300,
        'real_price' => 6000,
        'image' => 'item/Arumi ring.jpg',
        'category_id' => 2,
        'seller_id' => 5,
      ],
      [
        'name' => 'Flower Ring',
        'slug' => str()->slug('31-flower ring'),
        'price' => 6300,
        'real_price' => 6000,
        'image' => 'item/Flower Ring.jpg',
        'category_id' => 2,
        'seller_id' => 5,
      ],
      [
        'name' => 'Nudey Ring',
        'slug' => str()->slug('31-nudey ring'),
        'price' => 6300,
        'real_price' => 6000,
        'image' => 'item/Nudey Ring.jpg',
        'category_id' => 2,
        'seller_id' => 5,
      ],
      [
        'name' => 'Starbie Ring',
        'slug' => str()->slug('31-starbie ring'),
        'price' => 6300,
        'real_price' => 6000,
        'image' => 'item/Starbie Ring.jpg',
        'category_id' => 2,
        'seller_id' => 5,
      ],
      [
        'name' => 'Black Series Ring',
        'slug' => str()->slug('31-black series ring'),
        'price' => 6300,
        'real_price' => 6000,
        'image' => 'item/Black Series Ring.jpg',
        'category_id' => 2,
        'seller_id' => 5,
      ],
      [
        'name' => 'Sweet Joa Ring',
        'slug' => str()->slug('31-sweet joa ring'),
        'price' => 10500,
        'real_price' => 10000,
        'image' => 'item/Sweet Joa Ring.jpg',
        'category_id' => 2,
        'seller_id' => 5,
      ],
      [
        'name' => 'Sweet Cleo Ring',
        'slug' => str()->slug('31-sweet cleo ring'),
        'price' => 10500,
        'real_price' => 10000,
        'image' => 'item/Sweet Cleo Ring.jpeg',
        'category_id' => 2,
        'seller_id' => 5,
      ],
      [
        'name' => 'Couple Bracelet',
        'slug' => str()->slug('31-couple bracelet'),
        'price' => 31500,
        'real_price' => 30000,
        'image' => 'item/Couple Bracelet.jpg',
        'category_id' => 2,
        'seller_id' => 5,
      ],
      [
        'name' => 'Celina Bracelet',
        'slug' => str()->slug('31-celina bracelet'),
        'price' => 16800,
        'real_price' => 16000,
        'image' => 'item/Celina Bracelet.jpg',
        'category_id' => 2,
        'seller_id' => 5,
      ],
      [
        'name' => 'Aeri Bracelet',
        'slug' => str()->slug('31-aeri bracelet'),
        'price' => 17850,
        'real_price' => 17000,
        'image' => 'item/Aeri Bracelet.jpg',
        'category_id' => 2,
        'seller_id' => 5,
      ],
      [
        'name' => 'Ciela Bracelet',
        'slug' => str()->slug('31-ciela bracelet'),
        'price' => 17850,
        'real_price' => 17000,
        'image' => 'item/Ciela Bracelet.jpg',
        'category_id' => 2,
        'seller_id' => 5,
      ],
      [
        'name' => 'Darla Bracelet',
        'slug' => str()->slug('31-darla bracelet'),
        'price' => 17850,
        'real_price' => 17000,
        'image' => 'item/Darla Bracelet.jpg',
        'category_id' => 2,
        'seller_id' => 5,
      ],
      [
        'name' => 'Saski Bracelet',
        'slug' => str()->slug('31-saski bracelet'),
        'price' => 17850,
        'real_price' => 17000,
        'image' => 'item/Saski Bracelet.jpg',
        'category_id' => 2,
        'seller_id' => 5,
      ],
      [
        'name' => 'Oliv Bracelet',
        'slug' => str()->slug('31-oliv bracelet'),
        'price' => 16800,
        'real_price' => 16000,
        'image' => 'item/Oliv Bracelet.jpg',
        'category_id' => 2,
        'seller_id' => 5,
      ],
      [
        'name' => 'Sean Bracelet',
        'slug' => str()->slug('31-sean bracelet'),
        'price' => 16800,
        'real_price' => 16000,
        'image' => 'item/Sean Bracelet.jpeg',
        'category_id' => 2,
        'seller_id' => 5,
      ],
      [
        'name' => 'Phone Hook',
        'slug' => str()->slug('31-phone hook'),
        'price' => 36750,
        'real_price' => 35000,
        'image' => 'item/Phone Hook.jpg',
        'category_id' => 2,
        'seller_id' => 5,
      ],
      [
        'name' => 'Hera Phone Strap',
        'slug' => str()->slug('31-hera phone strap'),
        'price' => 44100,
        'real_price' => 42000,
        'image' => 'item/Hera Phone Strap.jpg',
        'category_id' => 2,
        'seller_id' => 5,
      ],
      [
        'name' => 'Cassie Phone Strap',
        'slug' => str()->slug('31-cassie phone strap'),
        'price' => 44100,
        'real_price' => 42000,
        'image' => 'item/Cassie Phone Strap.jpg',
        'category_id' => 2,
        'seller_id' => 5,
      ],
      [
        'name' => 'Lumi Phone Strap',
        'slug' => str()->slug('31-lumi phone strap'),
        'price' => 44100,
        'real_price' => 42000,
        'image' => 'item/Lumi Phone Strap.jpeg',
        'category_id' => 2,
        'seller_id' => 5,
      ],
      [
        'name' => 'Hazel Phone Strap',
        'slug' => str()->slug('31-hazel phone strap'),
        'price' => 44100,
        'real_price' => 42000,
        'image' => 'item/Hazel Phone Strap.jpg',
        'category_id' => 2,
        'seller_id' => 5,
      ],
      [
        'name' => 'Kopi Susu',
        'slug' => str()->slug('32-kopi susu'),
        'price' => 15750,
        'real_price' => 15000,
        'image' => 'item/Kopi Susu.png',
        'category_id' => 1,
        'seller_id' => 6,
      ],
      [
        'name' => 'Vietnam Drip',
        'slug' => str()->slug('32-vietnam drip'),
        'price' => 15750,
        'real_price' => 15000,
        'image' => 'item/Vietnam Drip.png',
        'category_id' => 1,
        'seller_id' => 6,
      ],
      [
        'name' => 'Serotonin',
        'slug' => str()->slug('32-serotonin'),
        'price' => 18900,
        'real_price' => 18000,
        'image' => 'item/Serotonin.png',
        'category_id' => 1,
        'seller_id' => 6,
      ],
      [
        'name' => 'Monkey Banana',
        'slug' => str()->slug('32-monkey banana'),
        'price' => 18900,
        'real_price' => 18000,
        'image' => 'item/Monkey Banana.png',
        'category_id' => 1,
        'seller_id' => 6,
      ],
      [
        'name' => 'Es Kopi Karamel',
        'slug' => str()->slug('32-es kopi karamel'),
        'price' => 18900,
        'real_price' => 18000,
        'image' => 'item/Es Kopi Karamel.png',
        'category_id' => 1,
        'seller_id' => 6,
      ],
      [
        'name' => 'Es Kopi Aren',
        'slug' => str()->slug('32-es kopi aren'),
        'price' => 18900,
        'real_price' => 18000,
        'image' => 'item/Es Kopi Aren.png',
        'category_id' => 1,
        'seller_id' => 6,
      ],
      [
        'name' => 'Es Kopi Susu',
        'slug' => str()->slug('32-es kopi susu'),
        'price' => 18900,
        'real_price' => 18000,
        'image' => 'item/Es Kopi Susu.jpeg',
        'category_id' => 1,
        'seller_id' => 6,
      ],
      [
        'name' => 'Green Tea',
        'slug' => str()->slug('32-green tea'),
        'price' => 15750,
        'real_price' => 15000,
        'image' => 'item/Green Tea.png',
        'category_id' => 1,
        'seller_id' => 6,
      ],
      [
        'name' => 'Lemon Tea',
        'slug' => str()->slug('32-lemon tea'),
        'price' => 15750,
        'real_price' => 15000,
        'image' => 'item/Lemon Tea.png',
        'category_id' => 1,
        'seller_id' => 6,
      ],
      [
        'name' => 'Es Lotus',
        'slug' => str()->slug('32-es lotus'),
        'price' => 21000,
        'real_price' => 20000,
        'image' => 'item/Es Lotus.png',
        'category_id' => 1,
        'seller_id' => 6,
      ],
      [
        'name' => 'Nasi Ayam Kemangi',
        'slug' => str()->slug('32-nasi ayam kemangi'),
        'price' => 15750,
        'real_price' => 15000,
        'image' => 'item/Nasi Ayam Kemangi.png',
        'category_id' => 1,
        'seller_id' => 6,
      ],
      [
        'name' => 'Pisang Original',
        'slug' => str()->slug('32-pisang original'),
        'price' => 10500,
        'real_price' => 10000,
        'image' => 'item/Pisang Original.png',
        'category_id' => 1,
        'seller_id' => 6,
      ],
      [
        'name' => 'Pisang Keju Susu',
        'slug' => str()->slug('32-pisang keju susu'),
        'price' => 15750,
        'real_price' => 15000,
        'image' => 'item/Pisang Keju Susu.png',
        'category_id' => 1,
        'seller_id' => 6,
      ],
      [
        'name' => 'Kentang Goreng',
        'slug' => str()->slug('32-kentang goreng'),
        'price' => 21000,
        'real_price' => 20000,
        'image' => 'item/Kentang Goreng.png',
        'category_id' => 1,
        'seller_id' => 6,
      ],
      [
        'name' => 'Chicken Katsu',
        'slug' => str()->slug('33-chicken katsu'),
        'price' => 21000,
        'real_price' => 20000,
        'image' => 'item/Chicken Katsu.png',
        'category_id' => 1,
        'seller_id' => 7,
      ],
      [
        'name' => 'Chicken Steak',
        'slug' => str()->slug('33-chicken steak'),
        'price' => 26250,
        'real_price' => 25000,
        'image' => 'item/Chicken Steak.png',
        'category_id' => 1,
        'seller_id' => 7,
      ],
      [
        'name' => 'Beef Burger',
        'slug' => str()->slug('33-beef burger'),
        'price' => 21000,
        'real_price' => 20000,
        'image' => 'item/Beef Burger.png',
        'category_id' => 1,
        'seller_id' => 7,
      ],
      [
        'name' => 'Hotdog Cheese Beef',
        'slug' => str()->slug('33-hotdog cheese beef'),
        'price' => 21000,
        'real_price' => 20000,
        'image' => 'item/Hotdog Cheese Beef.png',
        'category_id' => 1,
        'seller_id' => 7,
      ],
      [
        'name' => 'Risol Mayo',
        'slug' => str()->slug('34-risol mayo'),
        'price' => 15750,
        'real_price' => 15000,
        'image' => 'item/Risol Mayo.png',
        'category_id' => 1,
        'seller_id' => 8,
      ],
      [
        'name' => 'Banana Roll Matcha',
        'slug' => str()->slug('34-banana roll matcha'),
        'price' => 10500,
        'real_price' => 10000,
        'image' => 'item/Banana Roll Matcha.png',
        'category_id' => 1,
        'seller_id' => 8,
      ],
      [
        'name' => 'Banana Roll Coklat',
        'slug' => str()->slug('34-banana roll coklat'),
        'price' => 10500,
        'real_price' => 10000,
        'image' => 'item/Banana Roll Coklat.png',
        'category_id' => 1,
        'seller_id' => 8,
      ],
      [
        'name' => 'Banana Roll Keju',
        'slug' => str()->slug('34-banana roll keju'),
        'price' => 10500,
        'real_price' => 10000,
        'image' => 'item/Banana Roll Keju.png',
        'category_id' => 1,
        'seller_id' => 8,
      ],
      [
        'name' => 'Banana Roll Mix',
        'slug' => str()->slug('34-banana roll mix'),
        'price' => 15750,
        'real_price' => 15000,
        'image' => 'item/Banana Roll Mix.png',
        'category_id' => 1,
        'seller_id' => 8,
      ],
      [
        'name' => 'Pisang Coklat',
        'slug' => str()->slug('34-pisang coklat'),
        'price' => 26250,
        'real_price' => 25000,
        'image' => 'item/Pisang Coklat.png',
        'category_id' => 1,
        'seller_id' => 8,
      ],
      [
        'name' => 'Pisang Ori',
        'slug' => str()->slug('34-pisang ori'),
        'price' => 21000,
        'real_price' => 20000,
        'image' => 'item/Pisang Ori.png',
        'category_id' => 1,
        'seller_id' => 8,
      ],
      [
        'name' => 'Ice Greentea Senja',
        'slug' => str()->slug('34-ice greentea senja'),
        'price' => 10500,
        'real_price' => 10000,
        'image' => 'item/Ice Greentea Senja.png',
        'category_id' => 1,
        'seller_id' => 8,
      ],
      [
        'name' => 'Ice Coklat Senja',
        'slug' => str()->slug('34-ice coklat senja'),
        'price' => 10500,
        'real_price' => 10000,
        'image' => 'item/Ice Coklat Senja.png',
        'category_id' => 1,
        'seller_id' => 8,
      ],
      [
        'name' => 'Ice Strawberry',
        'slug' => str()->slug('34-ice strawberry'),
        'price' => 10500,
        'real_price' => 10000,
        'image' => 'item/Ice Strawberry.jpg',
        'category_id' => 1,
        'seller_id' => 8,
      ],
      [
        'name' => 'Ice Vanilla Senja',
        'slug' => str()->slug('34-ice vanilla senja'),
        'price' => 10500,
        'real_price' => 10000,
        'image' => 'item/Ice Vanilla Senja.png',
        'category_id' => 1,
        'seller_id' => 8,
      ],
      [
        'name' => 'Mie Goreng Telur',
        'slug' => str()->slug('35-mie goreng telur'),
        'price' => 12600,
        'real_price' => 12000,
        'image' => 'item/Mie Goreng Telur.png',
        'category_id' => 1,
        'seller_id' => 9,
      ],
      [
        'name' => 'Mie Goreng Bakso',
        'slug' => str()->slug('35-mie goreng bakso'),
        'price' => 15750,
        'real_price' => 15000,
        'image' => 'item/Mie Goreng Bakso.jpg',
        'category_id' => 1,
        'seller_id' => 9,
      ],
      [
        'name' => 'Mie Kuah',
        'slug' => str()->slug('35-mie kuah'),
        'price' => 15750,
        'real_price' => 15000,
        'image' => 'item/Mie Kuah.jpg',
        'category_id' => 1,
        'seller_id' => 9,
      ],
      [
        'name' => 'Mie Petir',
        'slug' => str()->slug('35-mie petir'),
        'price' => 17850,
        'real_price' => 17000,
        'image' => 'item/Mie Petir.png',
        'category_id' => 1,
        'seller_id' => 9,
      ],
      [
        'name' => 'Mie Nyemek',
        'slug' => str()->slug('35-mie nyemek'),
        'price' => 17850,
        'real_price' => 17000,
        'image' => 'item/Mie Nyemek.jpg',
        'category_id' => 1,
        'seller_id' => 9,
      ],
      [
        'name' => 'Seblak',
        'slug' => str()->slug('35-seblak'),
        'price' => 21000,
        'real_price' => 20000,
        'image' => 'item/Seblak.png',
        'category_id' => 1,
        'seller_id' => 9,
      ],
      [
        'name' => 'Bakso Bakar',
        'slug' => str()->slug('35-bakso bakar'),
        'price' => 15750,
        'real_price' => 15000,
        'image' => 'item/Bakso Bakar.jpg',
        'category_id' => 1,
        'seller_id' => 9,
      ],
      [
        'name' => 'Bakso Goreng',
        'slug' => str()->slug('35-bakso goreng'),
        'price' => 15750,
        'real_price' => 15000,
        'image' => 'item/Bakso Goreng.jpg',
        'category_id' => 1,
        'seller_id' => 9,
      ],
      [
        'name' => 'Bakso Kuah',
        'slug' => str()->slug('35-bakso kuah'),
        'price' => 15750,
        'real_price' => 15000,
        'image' => 'item/Bakso Kuah.jpg',
        'category_id' => 1,
        'seller_id' => 9,
      ],
      [
        'name' => 'Nasi Goreng',
        'slug' => str()->slug('35-nasi goreng'),
        'price' => 21000,
        'real_price' => 20000,
        'image' => 'item/Nasi Goreng.jpg',
        'category_id' => 1,
        'seller_id' => 9,
      ],
      [
        'name' => 'Burger',
        'slug' => str()->slug('35-burger'),
        'price' => 21000,
        'real_price' => 20000,
        'image' => 'item/Burger.jpg',
        'category_id' => 1,
        'seller_id' => 9,
      ],
      [
        'name' => 'Ayam Goreng Crispy',
        'slug' => str()->slug('35-ayam goreng crispy'),
        'price' => 31500,
        'real_price' => 30000,
        'image' => 'item/Ayam Goreng Crispy.jpg',
        'category_id' => 1,
        'seller_id' => 9,
      ],
      [
        'name' => 'Ayam Geprek',
        'slug' => str()->slug('35-ayam geprek'),
        'price' => 31500,
        'real_price' => 30000,
        'image' => 'item/Ayam Geprek.jpg',
        'category_id' => 1,
        'seller_id' => 9,
      ],
      [
        'name' => 'Ayam Lalapan',
        'slug' => str()->slug('35-ayam lalapan'),
        'price' => 12600,
        'real_price' => 12000,
        'image' => 'item/Ayam Lalapan.jpg',
        'category_id' => 1,
        'seller_id' => 9,
      ],
      [
        'name' => 'Pisang Goreng Keju',
        'slug' => str()->slug('35-pisang goreng keju'),
        'price' => 12600,
        'real_price' => 12000,
        'image' => 'item/Pisang Goreng Keju.png',
        'category_id' => 1,
        'seller_id' => 9,
      ],
      [
        'name' => 'Pisang Nugget',
        'slug' => str()->slug('35-pisang nugget'),
        'price' => 17850,
        'real_price' => 17000,
        'image' => 'item/Pisang Nugget.jpg',
        'category_id' => 1,
        'seller_id' => 9,
      ],
      [
        'name' => 'Pisang Epe',
        'slug' => str()->slug('35-pisang epe'),
        'price' => 15750,
        'real_price' => 15000,
        'image' => 'item/Pisang Epe.jpg',
        'category_id' => 1,
        'seller_id' => 9,
      ],
      [
        'name' => 'Roti Bakar',
        'slug' => str()->slug('35-roti bakar'),
        'price' => 12600,
        'real_price' => 12000,
        'image' => 'item/Roti Bakar.jpg',
        'category_id' => 1,
        'seller_id' => 9,
      ],
      [
        'name' => 'Kentang Goreng Barokah',
        'slug' => str()->slug('35-kentang goreng barokah'),
        'price' => 12600,
        'real_price' => 12000,
        'image' => 'item/Kentang Goreng Barokah.jpg',
        'category_id' => 1,
        'seller_id' => 9,
      ],
      [
        'name' => 'Banana Roll',
        'slug' => str()->slug('35-banana roll'),
        'price' => 10500,
        'real_price' => 10000,
        'image' => 'item/Banana Roll.jpeg',
        'category_id' => 1,
        'seller_id' => 9,
      ],
      [
        'name' => 'Jus Alpukat',
        'slug' => str()->slug('35-jus alpukat'),
        'price' => 10500,
        'real_price' => 10000,
        'image' => 'item/Jus Alpukat.jpg',
        'category_id' => 1,
        'seller_id' => 9,
      ],
      [
        'name' => 'Jus Buah Naga',
        'slug' => str()->slug('35-jus buah naga'),
        'price' => 10500,
        'real_price' => 10000,
        'image' => 'item/Jus Buah Naga.jpg',
        'category_id' => 1,
        'seller_id' => 9,
      ],
      [
        'name' => 'Jus Apel',
        'slug' => str()->slug('35-jus apel'),
        'price' => 10500,
        'real_price' => 10000,
        'image' => 'item/Jus Apel.JPG',
        'category_id' => 1,
        'seller_id' => 9,
      ],
      [
        'name' => 'Jus Jeruk',
        'slug' => str()->slug('35-jus jeruk'),
        'price' => 10500,
        'real_price' => 10000,
        'image' => 'item/Jus Jeruk.jpg',
        'category_id' => 1,
        'seller_id' => 9,
      ],
      [
        'name' => 'Jus Melon',
        'slug' => str()->slug('35-jus melon'),
        'price' => 10500,
        'real_price' => 10000,
        'image' => 'item/Jus Melon.jpg',
        'category_id' => 1,
        'seller_id' => 9,
      ],
      [
        'name' => 'Ice Milo',
        'slug' => str()->slug('35-ice milo'),
        'price' => 15750,
        'real_price' => 15000,
        'image' => 'item/Ice Milo.jpg',
        'category_id' => 1,
        'seller_id' => 9,
      ],
      [
        'name' => 'Ice Cappuchino',
        'slug' => str()->slug('35-ice cappuchino'),
        'price' => 15750,
        'real_price' => 15000,
        'image' => 'item/Ice Cappuchino.png',
        'category_id' => 1,
        'seller_id' => 9,
      ],
      [
        'name' => 'Ice Vanilla',
        'slug' => str()->slug('35-ice vanilla'),
        'price' => 15750,
        'real_price' => 15000,
        'image' => 'item/Ice Vanilla.png',
        'category_id' => 1,
        'seller_id' => 9,
      ],
      [
        'name' => 'Ice Greentea',
        'slug' => str()->slug('35-ice greentea'),
        'price' => 15750,
        'real_price' => 15000,
        'image' => 'item/Ice Greentea.jpg',
        'category_id' => 1,
        'seller_id' => 9,
      ],
      [
        'name' => 'Ice Coklat',
        'slug' => str()->slug('35-ice coklat'),
        'price' => 15750,
        'real_price' => 15000,
        'image' => 'item/Ice Coklat.jpg',
        'category_id' => 1,
        'seller_id' => 9,
      ],
      [
        'name' => 'Paru Goreng Rica',
        'slug' => str()->slug('36-paru goreng rica'),
        'price' => 31500,
        'real_price' => 30000,
        'image' => 'item/Paru Goreng Rica.jpeg',
        'category_id' => 1,
        'seller_id' => 10,
      ],
      [
        'name' => 'Baby Cumi',
        'slug' => str()->slug('36-baby cumi'),
        'price' => 26250,
        'real_price' => 25000,
        'image' => 'item/Baby Cumi.jpg',
        'category_id' => 1,
        'seller_id' => 10,
      ],
      [
        'name' => 'Sambel Pete',
        'slug' => str()->slug('36-sambel pete'),
        'price' => 21000,
        'real_price' => 20000,
        'image' => 'item/Sambel Pete.jpeg',
        'category_id' => 1,
        'seller_id' => 10,
      ],
      [
        'name' => 'Ayam Suwir',
        'slug' => str()->slug('36-ayam suwir'),
        'price' => 26250,
        'real_price' => 25000,
        'image' => 'item/Ayam Suwir.jpg',
        'category_id' => 1,
        'seller_id' => 10,
      ],
      [
        'name' => 'Cakalang Suwir',
        'slug' => str()->slug('36-cakalang suwir'),
        'price' => 26250,
        'real_price' => 25000,
        'image' => 'item/Cakalang Suwir.jpg',
        'category_id' => 1,
        'seller_id' => 10,
      ],
      [
        'name' => 'Teri Medan',
        'slug' => str()->slug('36-teri medan'),
        'price' => 21000,
        'real_price' => 20000,
        'image' => 'item/Teri Medan.jpg',
        'category_id' => 1,
        'seller_id' => 10,
      ],
      [
        'name' => 'Sambal Bawang',
        'slug' => str()->slug('36-sambal bawang'),
        'price' => 15750,
        'real_price' => 15000,
        'image' => 'item/Sambal Bawang.png',
        'category_id' => 1,
        'seller_id' => 10,
      ],
      [
        'name' => 'Nasi Bakar Ayam',
        'slug' => str()->slug('37-nasi bakar ayam'),
        'price' => 15750,
        'real_price' => 15000,
        'image' => 'item/Nasi Bakar Ayam.png',
        'category_id' => 1,
        'seller_id' => 11,
      ],
      [
        'name' => 'Sate Sosis Sapi',
        'slug' => str()->slug('37-sate sosis sapi'),
        'price' => 5250,
        'real_price' => 5000,
        'image' => 'item/Sate Sosis Sapi.png',
        'category_id' => 1,
        'seller_id' => 11,
      ],
      [
        'name' => 'Sate Odeng',
        'slug' => str()->slug('37-sate odeng'),
        'price' => 5250,
        'real_price' => 5000,
        'image' => 'item/Sate Odeng.png',
        'category_id' => 1,
        'seller_id' => 11,
      ],
      [
        'name' => 'Sate Ayam',
        'slug' => str()->slug('37-sate ayam'),
        'price' => 5250,
        'real_price' => 5000,
        'image' => 'item/Sate Ayam.jpg',
        'category_id' => 1,
        'seller_id' => 11,
      ],
      [
        'name' => 'Sate Kembang Cumi',
        'slug' => str()->slug('37-sate kembang cumi'),
        'price' => 5250,
        'real_price' => 5000,
        'image' => 'item/Sate Kembang Cumi.png',
        'category_id' => 1,
        'seller_id' => 11,
      ],
      [
        'name' => 'Sate Bola Salmon',
        'slug' => str()->slug('37-sate bola salmon'),
        'price' => 5250,
        'real_price' => 5000,
        'image' => 'item/Sate Bola Salmon.png',
        'category_id' => 1,
        'seller_id' => 11,
      ],
      [
        'name' => 'Sate Bola Kepiting',
        'slug' => str()->slug('37-sate bola kepiting'),
        'price' => 5250,
        'real_price' => 5000,
        'image' => 'item/Sate Bola Kepiting.png',
        'category_id' => 1,
        'seller_id' => 11,
      ],
      [
        'name' => 'Sate Krupuk Pangsit',
        'slug' => str()->slug('37-sate krupuk pangsit'),
        'price' => 5250,
        'real_price' => 5000,
        'image' => 'item/Sate Krupuk Pangsit.png',
        'category_id' => 1,
        'seller_id' => 11,
      ],
      [
        'name' => 'Sate Bakso Lobster',
        'slug' => str()->slug('37-sate bakso lobster'),
        'price' => 5250,
        'real_price' => 5000,
        'image' => 'item/Sate Bakso Lobster.png',
        'category_id' => 1,
        'seller_id' => 11,
      ],
      [
        'name' => 'Telur Puyu Bacem',
        'slug' => str()->slug('37-telur puyu bacem'),
        'price' => 5250,
        'real_price' => 5000,
        'image' => 'item/Telur Puyu Bacem.png',
        'category_id' => 1,
        'seller_id' => 11,
      ],
      [
        'name' => 'Sosis Kentang',
        'slug' => str()->slug('38-sosis kentang'),
        'price' => 21000,
        'real_price' => 20000,
        'image' => 'item/Sosis Kentang.jpg',
        'category_id' => 1,
        'seller_id' => 12,
      ],
      [
        'name' => 'Kentang Goreng Kelapa Dua',
        'slug' => str()->slug('38-kentang goreng kelapa dua'),
        'price' => 15750,
        'real_price' => 15000,
        'image' => 'item/Kentang Goreng Kelapa Dua.png',
        'category_id' => 1,
        'seller_id' => 12,
      ],
      [
        'name' => 'Ubi Goreng',
        'slug' => str()->slug('38-ubi goreng'),
        'price' => 15750,
        'real_price' => 15000,
        'image' => 'item/Ubi Goreng.jpg',
        'category_id' => 1,
        'seller_id' => 12,
      ],
      [
        'name' => 'Ayam Goreng Gepur',
        'slug' => str()->slug('38-ayam goreng gepur'),
        'price' => 26250,
        'real_price' => 25000,
        'image' => 'item/Ayam Goreng Gepur.jpg',
        'category_id' => 1,
        'seller_id' => 12,
      ],
      [
        'name' => 'Sub Ubi',
        'slug' => str()->slug('38-sub ubi'),
        'price' => 17850,
        'real_price' => 17000,
        'image' => 'item/Sup Ubi.jpg',
        'category_id' => 1,
        'seller_id' => 12,
      ],
      [
        'name' => 'Mie Goreng Tek Tek',
        'slug' => str()->slug('38-mie goreng tek tek'),
        'price' => 21000,
        'real_price' => 20000,
        'image' => 'item/Mie Goreng Tek Tek.png',
        'category_id' => 1,
        'seller_id' => 12,
      ],
      [
        'name' => 'Mie Kuah Tek Tek',
        'slug' => str()->slug('38-mie kuah tek tek'),
        'price' => 21000,
        'real_price' => 20000,
        'image' => 'item/Mie Kuah Tek Tek.jpg',
        'category_id' => 1,
        'seller_id' => 12,
      ],
      [
        'name' => 'Milo Cheese Regal',
        'slug' => str()->slug('38-milo cheese regal'),
        'price' => 18900,
        'real_price' => 18000,
        'image' => 'item/Milo Cheese Regal.png',
        'category_id' => 1,
        'seller_id' => 12,
      ],
      [
        'name' => 'Milo Cheese Kacang',
        'slug' => str()->slug('38-milo cheese kacang'),
        'price' => 15750,
        'real_price' => 15000,
        'image' => 'item/Milo Cheese Kacang.png',
        'category_id' => 1,
        'seller_id' => 12,
      ],
      [
        'name' => 'Choco Oreo',
        'slug' => str()->slug('38-choco oreo'),
        'price' => 17850,
        'real_price' => 17000,
        'image' => 'item/Choco Oreo.jpg',
        'category_id' => 1,
        'seller_id' => 12,
      ],
      [
        'name' => 'Choco Regal',
        'slug' => str()->slug('38-choco regal'),
        'price' => 17850,
        'real_price' => 17000,
        'image' => 'item/Choco Regal.png',
        'category_id' => 1,
        'seller_id' => 12,
      ],
      [
        'name' => 'Choco Berry',
        'slug' => str()->slug('38-choco berry'),
        'price' => 17850,
        'real_price' => 17000,
        'image' => 'item/Choco Berry.png',
        'category_id' => 1,
        'seller_id' => 12,
      ],
      [
        'name' => 'Green Tea Ice',
        'slug' => str()->slug('38-green tea ice'),
        'price' => 17850,
        'real_price' => 17000,
        'image' => 'item/Greentea Ice.jpg',
        'category_id' => 1,
        'seller_id' => 12,
      ],
      [
        'name' => 'Thaitea Ice',
        'slug' => str()->slug('38-thaitea ice'),
        'price' => 15750,
        'real_price' => 15000,
        'image' => 'item/Thaitea Ice.png',
        'category_id' => 1,
        'seller_id' => 12,
      ],
      [
        'name' => 'Vanilla Regal',
        'slug' => str()->slug('38-vanilla regal'),
        'price' => 15750,
        'real_price' => 15000,
        'image' => 'item/Vanilla Regal.png',
        'category_id' => 1,
        'seller_id' => 12,
      ],
      [
        'name' => 'Vanilla Shake',
        'slug' => str()->slug('38-vanilla shake'),
        'price' => 17850,
        'real_price' => 17000,
        'image' => 'item/Vanilla Shake.jpg',
        'category_id' => 1,
        'seller_id' => 12,
      ],
      [
        'name' => 'Strawberry Shake',
        'slug' => str()->slug('38-strawberry shake'),
        'price' => 15750,
        'real_price' => 15000,
        'image' => 'item/Strawberry Shake.jpg',
        'category_id' => 1,
        'seller_id' => 12,
      ],
      [
        'name' => 'Keripik Emping',
        'slug' => str()->slug('39-keripik emping'),
        'price' => 15750,
        'real_price' => 15000,
        'image' => 'item/Keripik Emping.jpeg',
        'category_id' => 1,
        'seller_id' => 13,
      ],
      [
        'name' => 'Kacang Sembunyi',
        'slug' => str()->slug('39-kacang sembunyi'),
        'price' => 23100,
        'real_price' => 22000,
        'image' => 'item/Kacang Sembunyi.jpeg',
        'category_id' => 1,
        'seller_id' => 13,
      ],
      [
        'name' => 'Stick Keju',
        'slug' => str()->slug('39-stick keju'),
        'price' => 24150,
        'real_price' => 23000,
        'image' => 'item/Stick Keju.jpeg',
        'category_id' => 1,
        'seller_id' => 13,
      ],
      [
        'name' => 'Mente Sembunyi',
        'slug' => str()->slug('39-mente sembunyi'),
        'price' => 25200,
        'real_price' => 24000,
        'image' => 'item/Mente Sembunyi.jpeg',
        'category_id' => 1,
        'seller_id' => 13,
      ],
      [
        'name' => 'Mente Original',
        'slug' => str()->slug('39-mente original'),
        'price' => 54600,
        'real_price' => 52000,
        'image' => 'item/Mente Original.jpeg',
        'category_id' => 1,
        'seller_id' => 13,
      ],
      [
        'name' => 'Mente Caramel',
        'slug' => str()->slug('39-mente caramel'),
        'price' => 54600,
        'real_price' => 52000,
        'image' => 'item/Mente Caramel.jpeg',
        'category_id' => 1,
        'seller_id' => 13,
      ],
      [
        'name' => 'Mente Bawang',
        'slug' => str()->slug('39-mente bawang'),
        'price' => 54600,
        'real_price' => 52000,
        'image' => 'item/Mente Bawang.jpeg',
        'category_id' => 1,
        'seller_id' => 13,
      ],
      [
        'name' => 'Gula Semut Jahe Sachet',
        'slug' => str()->slug('39-gula semut jahe sachet'),
        'price' => 21000,
        'real_price' => 20000,
        'image' => 'item/Gula Semut Jahe Sachet.jpeg',
        'category_id' => 1,
        'seller_id' => 13,
      ],
      [
        'name' => 'Gula Semut Ori',
        'slug' => str()->slug('39-gula semut ori'),
        'price' => 36750,
        'real_price' => 35000,
        'image' => 'item/Gula Semut Ori.jpeg',
        'category_id' => 1,
        'seller_id' => 13,
      ],
      [
        'name' => 'Mente Kentaki',
        'slug' => str()->slug('39-mente kentaki'),
        'price' => 59850,
        'real_price' => 57000,
        'image' => 'item/Mente Kentaki.jpeg',
        'category_id' => 1,
        'seller_id' => 13,
      ],
      [
        'name' => 'Mente Gula Aren',
        'slug' => str()->slug('39-mente gula aren'),
        'price' => 59850,
        'real_price' => 57000,
        'image' => 'item/Mente Gula Aren.jpeg',
        'category_id' => 1,
        'seller_id' => 13,
      ],
      [
        'name' => 'Kopi Robusta',
        'slug' => str()->slug('39-kopi robusta'),
        'price' => 17850,
        'real_price' => 17000,
        'image' => 'item/Kopi Robusta.jpeg',
        'category_id' => 1,
        'seller_id' => 13,
      ],
      [
        'name' => 'Dofu Paket Isi 6',
        'slug' => str()->slug('40-dofu paket isi 6'),
        'price' => 18900,
        'real_price' => 18000,
        'image' => 'item/Dofu Paket Isi 6.jpg',
        'category_id' => 1,
        'seller_id' => 14,
      ],
      [
        'name' => 'Dofu Paket Isi 18',
        'slug' => str()->slug('40-dofu paket isi 18'),
        'price' => 50400,
        'real_price' => 48000,
        'image' => 'item/Dofu Paket Isi 18.jpg',
        'category_id' => 1,
        'seller_id' => 14,
      ],
      [
        'name' => 'Donut Gula',
        'slug' => str()->slug('40-donut gula'),
        'price' => 26250,
        'real_price' => 25000,
        'image' => 'item/Donut Gula.jpg',
        'category_id' => 1,
        'seller_id' => 14,
      ],
      [
        'name' => 'Donut Abon',
        'slug' => str()->slug('40-donut abon'),
        'price' => 4200,
        'real_price' => 4000,
        'image' => 'item/Donut Abon.jpg',
        'category_id' => 1,
        'seller_id' => 14,
      ],
      [
        'name' => 'Tart Mini',
        'slug' => str()->slug('40-tart mini'),
        'price' => 47250,
        'real_price' => 45000,
        'image' => 'item/Tart Mini.jpg',
        'category_id' => 1,
        'seller_id' => 14,
      ],
      [
        'name' => 'Brownies Toping',
        'slug' => str()->slug('40-brownies toping'),
        'price' => 68250,
        'real_price' => 65000,
        'image' => 'item/Brownies Toping.jpg',
        'category_id' => 1,
        'seller_id' => 14,
      ],
      [
        'name' => 'Bakso Goreng Uo',
        'slug' => str()->slug('41-bakso goreng uo'),
        'price' => 23100,
        'real_price' => 22000,
        'image' => 'item/Bakso Goreng Uo.jpg',
        'category_id' => 1,
        'seller_id' => 15,
      ],
      [
        'name' => 'Batagor',
        'slug' => str()->slug('41-batagor'),
        'price' => 26250,
        'real_price' => 25000,
        'image' => 'item/Batagor.jpg',
        'category_id' => 1,
        'seller_id' => 15,
      ],
      [
        'name' => 'Choco Hazelnut',
        'slug' => str()->slug('41-choco hazelnut'),
        'price' => 21000,
        'real_price' => 20000,
        'image' => 'item/Choco Hazelnut.jpg',
        'category_id' => 1,
        'seller_id' => 15,
      ],
      [
        'name' => 'Es Choco Oreo',
        'slug' => str()->slug('41-es choco oreo'),
        'price' => 21000,
        'real_price' => 20000,
        'image' => 'item/Es Choco Oreo.jpg',
        'category_id' => 1,
        'seller_id' => 15,
      ],
      [
        'name' => 'Es Kopi Uo',
        'slug' => str()->slug('41-es kopi uo'),
        'price' => 15750,
        'real_price' => 15000,
        'image' => 'item/Es Kopi Uo.jpg',
        'category_id' => 1,
        'seller_id' => 15,
      ],
      [
        'name' => 'Es Susu Aren',
        'slug' => str()->slug('41-es susu aren'),
        'price' => 15750,
        'real_price' => 15000,
        'image' => 'item/Es Susu Aren.jpg',
        'category_id' => 1,
        'seller_id' => 15,
      ],
      [
        'name' => 'Ice Tea',
        'slug' => str()->slug('41-ice tea'),
        'price' => 15750,
        'real_price' => 15000,
        'image' => 'item/Ice Tea.jpg',
        'category_id' => 1,
        'seller_id' => 15,
      ],
      [
        'name' => 'Kopi Pandan',
        'slug' => str()->slug('41-kopi pandan'),
        'price' => 24150,
        'real_price' => 23000,
        'image' => 'item/Kopi Pandan.jpg',
        'category_id' => 1,
        'seller_id' => 15,
      ],
      [
        'name' => 'Mie Kering',
        'slug' => str()->slug('41-mie kering'),
        'price' => 21000,
        'real_price' => 20000,
        'image' => 'item/Mie Kering.jpg',
        'category_id' => 1,
        'seller_id' => 15,
      ],
      [
        'name' => 'Mie Pangsit',
        'slug' => str()->slug('41-mie pangsit'),
        'price' => 26250,
        'real_price' => 25000,
        'image' => 'item/Mie Pangsit.jpg',
        'category_id' => 1,
        'seller_id' => 15,
      ],
      [
        'name' => 'Nasi Goreng Uo',
        'slug' => str()->slug('41-nasi goreng uo'),
        'price' => 27300,
        'real_price' => 26000,
        'image' => 'item/Nasi Goreng Uo.jpg',
        'category_id' => 1,
        'seller_id' => 15,
      ],
      [
        'name' => 'Pancake Keju',
        'slug' => str()->slug('41-pancake keju'),
        'price' => 28350,
        'real_price' => 27000,
        'image' => 'item/Pancake Keju.jpg',
        'category_id' => 1,
        'seller_id' => 15,
      ],
      [
        'name' => 'Pancake UO',
        'slug' => str()->slug('41-pancake uo'),
        'price' => 27300,
        'real_price' => 26000,
        'image' => 'item/Pancake UO.jpg',
        'category_id' => 1,
        'seller_id' => 15,
      ],
      [
        'name' => 'Rice Bool',
        'slug' => str()->slug('41-rice bool'),
        'price' => 28350,
        'real_price' => 27000,
        'image' => 'item/Rice Bool.jpg',
        'category_id' => 1,
        'seller_id' => 15,
      ],
      [
        'name' => 'Risoles Uo',
        'slug' => str()->slug('41-risoles uo'),
        'price' => 26250,
        'real_price' => 25000,
        'image' => 'item/Risoles Uo.jpg',
        'category_id' => 1,
        'seller_id' => 15,
      ],
      [
        'name' => 'Sky Cold',
        'slug' => str()->slug('41-sky cold'),
        'price' => 15750,
        'real_price' => 15000,
        'image' => 'item/Sky Cold.jpg',
        'category_id' => 1,
        'seller_id' => 15,
      ],
      [
        'name' => 'Vanilla Regal Uo',
        'slug' => str()->slug('41-vanilla regal uo'),
        'price' => 21000,
        'real_price' => 20000,
        'image' => 'item/Vanilla Regal Uo.jpg',
        'category_id' => 1,
        'seller_id' => 15,
      ],
      [
        'name' => 'Kari Ayam',
        'slug' => str()->slug('42-kari ayam'),
        'price' => 21000,
        'real_price' => 20000,
        'image' => 'item/Kari Ayam.jpg',
        'category_id' => 1,
        'seller_id' => 16,
      ],
      [
        'name' => 'Ayam Geprek Ummu',
        'slug' => str()->slug('42-ayam geprek ummu'),
        'price' => 26250,
        'real_price' => 25000,
        'image' => 'item/Ayam Geprek Ummu.jpg',
        'category_id' => 1,
        'seller_id' => 16,
      ],
      [
        'name' => 'Ayam Ungkep',
        'slug' => str()->slug('42-ayam ungkep'),
        'price' => 68250,
        'real_price' => 65000,
        'image' => 'item/Ayam Ungkep.jpg',
        'category_id' => 1,
        'seller_id' => 16,
      ],
      [
        'name' => 'Ayam Bakar',
        'slug' => str()->slug('42-ayam bakar'),
        'price' => 26250,
        'real_price' => 25000,
        'image' => 'item/Ayam Bakar.jpg',
        'category_id' => 1,
        'seller_id' => 16,
      ],
      [
        'name' => 'Telur Geprek',
        'slug' => str()->slug('42-telur geprek'),
        'price' => 15750,
        'real_price' => 15000,
        'image' => 'item/Telur Geprek.jpg',
        'category_id' => 1,
        'seller_id' => 16,
      ],
      [
        'name' => 'Tempe Geprek',
        'slug' => str()->slug('42-tempe geprek'),
        'price' => 15750,
        'real_price' => 15000,
        'image' => 'item/Tempe Geprek.jpg',
        'category_id' => 1,
        'seller_id' => 16,
      ],
      [
        'name' => 'Pangsit Goreng',
        'slug' => str()->slug('42-pangsit goreng'),
        'price' => 21000,
        'real_price' => 20000,
        'image' => 'item/Pangsit Goreng.jpg',
        'category_id' => 1,
        'seller_id' => 16,
      ],
      [
        'name' => 'Martabak Mie',
        'slug' => str()->slug('42-martabak mie'),
        'price' => 15750,
        'real_price' => 15000,
        'image' => 'item/Martabak Mie.jpeg',
        'category_id' => 1,
        'seller_id' => 16,
      ],
      [
        'name' => 'Nasi Ikan',
        'slug' => str()->slug('42-nasi ikan'),
        'price' => 15750,
        'real_price' => 15000,
        'image' => 'item/Nasi Ikan.jpg',
        'category_id' => 1,
        'seller_id' => 16,
      ],
      [
        'name' => 'Dangkot Ayam',
        'slug' => str()->slug('42-dangkot ayam'),
        'price' => 26250,
        'real_price' => 25000,
        'image' => 'item/Dangkot Ayam.jpg',
        'category_id' => 1,
        'seller_id' => 16,
      ],
      [
        'name' => 'Chicken Pop',
        'slug' => str()->slug('43-chicken pop'),
        'price' => 26250,
        'real_price' => 25000,
        'image' => 'item/Chicken Pop.jpg',
        'category_id' => 1,
        'seller_id' => 17,
      ],
      [
        'name' => 'Choco Nutty',
        'slug' => str()->slug('43-choco nutty'),
        'price' => 21000,
        'real_price' => 20000,
        'image' => 'item/Choco Nutty.jpg',
        'category_id' => 1,
        'seller_id' => 17,
      ],
      [
        'name' => 'Fresh Lemon Tea',
        'slug' => str()->slug('43-fresh lemon tea'),
        'price' => 21000,
        'real_price' => 20000,
        'image' => 'item/Fresh Lemon Tea.jpg',
        'category_id' => 1,
        'seller_id' => 17,
      ],
      [
        'name' => 'Hot Kopi Aren',
        'slug' => str()->slug('43-hot kopi aren'),
        'price' => 18900,
        'real_price' => 18000,
        'image' => 'item/Hot Kopi Aren.jpg',
        'category_id' => 1,
        'seller_id' => 17,
      ],
      [
        'name' => 'Ice Matcha',
        'slug' => str()->slug('43-ice matcha'),
        'price' => 21000,
        'real_price' => 20000,
        'image' => 'item/Ice Matcha.jpg',
        'category_id' => 1,
        'seller_id' => 17,
      ],
      [
        'name' => 'Kopi Susu My',
        'slug' => str()->slug('43-kopi susu my'),
        'price' => 18900,
        'real_price' => 18000,
        'image' => 'item/Kopi Susu My.jpg',
        'category_id' => 1,
        'seller_id' => 17,
      ],
      [
        'name' => 'Lime Juice',
        'slug' => str()->slug('43-lime juice'),
        'price' => 23100,
        'real_price' => 22000,
        'image' => 'item/Lime Juice.jpg',
        'category_id' => 1,
        'seller_id' => 17,
      ],
      [
        'name' => 'Mie Kuah My',
        'slug' => str()->slug('43-mie kuah my'),
        'price' => 21000,
        'real_price' => 20000,
        'image' => 'item/Mie Kuah My.jpg',
        'category_id' => 1,
        'seller_id' => 17,
      ],
      [
        'name' => 'Milk Tea',
        'slug' => str()->slug('43-milk tea'),
        'price' => 18900,
        'real_price' => 18000,
        'image' => 'item/Milk Tea.jpg',
        'category_id' => 1,
        'seller_id' => 17,
      ],
      [
        'name' => 'Nasi Goreng My',
        'slug' => str()->slug('43-nasi goreng my'),
        'price' => 28350,
        'real_price' => 27000,
        'image' => 'item/Nasi Goreng My.jpg',
        'category_id' => 1,
        'seller_id' => 17,
      ],
      [
        'name' => 'Nasi Telur Dadar',
        'slug' => str()->slug('43-nasi telur dadar'),
        'price' => 24150,
        'real_price' => 23000,
        'image' => 'item/Nasi Telur Dadar.jpg',
        'category_id' => 1,
        'seller_id' => 17,
      ],
      [
        'name' => 'Rice Bool Rica Rica',
        'slug' => str()->slug('43-rice bool rica rica'),
        'price' => 29400,
        'real_price' => 28000,
        'image' => 'item/Rice Bool Rica Rica.jpg',
        'category_id' => 1,
        'seller_id' => 17,
      ],
      [
        'name' => 'Afogatto',
        'slug' => str()->slug('44-afogatto'),
        'price' => 21000,
        'real_price' => 20000,
        'image' => 'item/Afogatto.jpg',
        'category_id' => 1,
        'seller_id' => 18,
      ],
      [
        'name' => 'Blueberry Ice',
        'slug' => str()->slug('44-blueberry ice'),
        'price' => 21000,
        'real_price' => 20000,
        'image' => 'item/Blueberry Ice.jpg',
        'category_id' => 1,
        'seller_id' => 18,
      ],
      [
        'name' => 'Cappuchino Hot',
        'slug' => str()->slug('44-cappuchino hot'),
        'price' => 21000,
        'real_price' => 20000,
        'image' => 'item/Cappuchino Hot.jpg',
        'category_id' => 1,
        'seller_id' => 18,
      ],
      [
        'name' => 'Greentea Ice Story',
        'slug' => str()->slug('44-greentea ice story'),
        'price' => 15750,
        'real_price' => 15000,
        'image' => 'item/Greentea Ice Story.jpg',
        'category_id' => 1,
        'seller_id' => 18,
      ],
      [
        'name' => 'Ice Americano',
        'slug' => str()->slug('44-ice americano'),
        'price' => 21000,
        'real_price' => 20000,
        'image' => 'item/Ice Americano.jpg',
        'category_id' => 1,
        'seller_id' => 18,
      ],
      [
        'name' => 'Ice Brown Sugar',
        'slug' => str()->slug('44-ice brown sugar'),
        'price' => 15750,
        'real_price' => 15000,
        'image' => 'item/Ice Brown Sugar.jpg',
        'category_id' => 1,
        'seller_id' => 18,
      ],
      [
        'name' => 'Ice Coffee',
        'slug' => str()->slug('44-ice coffee'),
        'price' => 15750,
        'real_price' => 15000,
        'image' => 'item/Ice Coffee.jpg',
        'category_id' => 1,
        'seller_id' => 18,
      ],
      [
        'name' => 'Ice Milo Story',
        'slug' => str()->slug('44-ice milo story'),
        'price' => 15750,
        'real_price' => 15000,
        'image' => 'item/Ice Milo Story.jpg',
        'category_id' => 1,
        'seller_id' => 18,
      ],
      [
        'name' => 'Jasuke',
        'slug' => str()->slug('44-jasuke'),
        'price' => 15750,
        'real_price' => 15000,
        'image' => 'item/Jasuke.jpg',
        'category_id' => 1,
        'seller_id' => 18,
      ],
      [
        'name' => 'Kopi Aren Story',
        'slug' => str()->slug('44-kopi aren story'),
        'price' => 15750,
        'real_price' => 15000,
        'image' => 'item/Kopi Aren Story.jpg',
        'category_id' => 1,
        'seller_id' => 18,
      ],
      [
        'name' => 'Kopi Susu Story',
        'slug' => str()->slug('44-kopi susu story'),
        'price' => 15750,
        'real_price' => 15000,
        'image' => 'item/Kopi Susu Story.jpg',
        'category_id' => 1,
        'seller_id' => 18,
      ],
      [
        'name' => 'Lime Tea',
        'slug' => str()->slug('44-lime tea'),
        'price' => 15750,
        'real_price' => 15000,
        'image' => 'item/Lime Tea.jpg',
        'category_id' => 1,
        'seller_id' => 18,
      ],
      [
        'name' => 'Mie Tik Tik',
        'slug' => str()->slug('44-mie tik tik'),
        'price' => 26250,
        'real_price' => 25000,
        'image' => 'item/Mie Tik Tik.jpg',
        'category_id' => 1,
        'seller_id' => 18,
      ],
      [
        'name' => 'Nasi Ayam Story',
        'slug' => str()->slug('44-nasi ayam story'),
        'price' => 26250,
        'real_price' => 25000,
        'image' => 'item/Nasi Ayam Story.jpg',
        'category_id' => 1,
        'seller_id' => 18,
      ],
      [
        'name' => 'Nasi Goreng Kampung Story',
        'slug' => str()->slug('44-nasi goreng kampung story'),
        'price' => 21000,
        'real_price' => 20000,
        'image' => 'item/Nasi Goreng Kampung Story.jpg',
        'category_id' => 1,
        'seller_id' => 18,
      ],
      [
        'name' => 'Nasi Rendang',
        'slug' => str()->slug('44-nasi rendang'),
        'price' => 31500,
        'real_price' => 30000,
        'image' => 'item/Nasi Rendang.jpg',
        'category_id' => 1,
        'seller_id' => 18,
      ],
      [
        'name' => 'Sop Iga',
        'slug' => str()->slug('44-sop iga'),
        'price' => 36750,
        'real_price' => 35000,
        'image' => 'item/Sop Iga.jpg',
        'category_id' => 1,
        'seller_id' => 18,
      ],
      [
        'name' => 'Soto Lamongan',
        'slug' => str()->slug('44-soto lamongan'),
        'price' => 26250,
        'real_price' => 25000,
        'image' => 'item/Soto Lamongan.jpg',
        'category_id' => 1,
        'seller_id' => 18,
      ],
      [
        'name' => 'Tahu Mercon',
        'slug' => str()->slug('44-tahu mercon'),
        'price' => 26250,
        'real_price' => 25000,
        'image' => 'item/Tahu Mercon.jpg',
        'category_id' => 1,
        'seller_id' => 18,
      ],
      [
        'name' => 'V60',
        'slug' => str()->slug('44-v60'),
        'price' => 21000,
        'real_price' => 20000,
        'image' => 'item/V60.jpg',
        'category_id' => 1,
        'seller_id' => 18,
      ],
      [
        'name' => 'Nasi Lalapan',
        'slug' => str()->slug('44-nasi lalapan'),
        'price' => 26250,
        'real_price' => 25000,
        'image' => 'item/Nasi Lalapan.jpg',
        'category_id' => 1,
        'seller_id' => 18,
      ],
      [
        'name' => 'Nasi Ayam Geprek',
        'slug' => str()->slug('45-nasi ayam geprek'),
        'price' => 21000,
        'real_price' => 20000,
        'image' => 'item/Nasi Ayam Geprek.jpg',
        'category_id' => 1,
        'seller_id' => 19,
      ],
      [
        'name' => 'Nasi Ayam Rica Rica',
        'slug' => str()->slug('45-nasi ayam rica rica'),
        'price' => 31500,
        'real_price' => 30000,
        'image' => 'item/Nasi Ayam Rica Rica.jpg',
        'category_id' => 1,
        'seller_id' => 19,
      ],
      [
        'name' => 'Ikan Bakar Rica Rica',
        'slug' => str()->slug('45-ikan bakar rica rica'),
        'price' => 42000,
        'real_price' => 40000,
        'image' => 'item/Ikan Bakar Rica Rica.jpg',
        'category_id' => 1,
        'seller_id' => 19,
      ],
      [
        'name' => 'Ikan Bakar Parape',
        'slug' => str()->slug('45-ikan bakar parape'),
        'price' => 31500,
        'real_price' => 30000,
        'image' => 'item/Ikan Bakar Parape.jpg',
        'category_id' => 1,
        'seller_id' => 19,
      ],
      [
        'name' => 'Ikan Bakar Bolu',
        'slug' => str()->slug('45-ikan bakar bolu'),
        'price' => 36750,
        'real_price' => 35000,
        'image' => 'item/Ikan Bakar Bolu.jpg',
        'category_id' => 1,
        'seller_id' => 19,
      ],
      [
        'name' => 'Cumi Parape',
        'slug' => str()->slug('45-cumi parape'),
        'price' => 42000,
        'real_price' => 40000,
        'image' => 'item/Cumi Parape.jpg',
        'category_id' => 1,
        'seller_id' => 19,
      ],
      [
        'name' => 'Kangkung Tumis',
        'slug' => str()->slug('45-kangkung tumis'),
        'price' => 42000,
        'real_price' => 40000,
        'image' => 'item/Kangkung Tumis.jpg',
        'category_id' => 1,
        'seller_id' => 19,
      ],
      [
        'name' => 'Kepiting Hambur',
        'slug' => str()->slug('45-kepiting hambur'),
        'price' => 42000,
        'real_price' => 40000,
        'image' => 'item/Kepiting Hambur.jpg',
        'category_id' => 1,
        'seller_id' => 19,
      ],
      [
        'name' => 'Udang Bakar',
        'slug' => str()->slug('45-udang bakar'),
        'price' => 15750,
        'real_price' => 15000,
        'image' => 'item/Udang Bakar.jpg',
        'category_id' => 1,
        'seller_id' => 19,
      ],
      [
        'name' => 'Blouse Cerrutty Premium',
        'slug' => str()->slug('46-blouse cerrutty premium'),
        'price' => 136500,
        'real_price' => 130000,
        'image' => 'item/Blouse Cerrutty Premium.jpg',
        'category_id' => 3,
        'seller_id' => 20,
      ],
      [
        'name' => 'Switer Katun Oversize',
        'slug' => str()->slug('46-switer katun oversize'),
        'price' => 157500,
        'real_price' => 150000,
        'image' => 'item/Switer Katun Oversize.jpg',
        'category_id' => 3,
        'seller_id' => 20,
      ],
      [
        'name' => 'Hoodie Soat Roge',
        'slug' => str()->slug('46-hoodie soat roge'),
        'price' => 157500,
        'real_price' => 150000,
        'image' => 'item/Hoodie Soat Roge.jpg',
        'category_id' => 3,
        'seller_id' => 20,
      ],
      [
        'name' => 'Kemeja Salur Katun',
        'slug' => str()->slug('46-kemeja salur katun'),
        'price' => 115500,
        'real_price' => 110000,
        'image' => 'item/Kemeja Salur Katun.jpg',
        'category_id' => 3,
        'seller_id' => 20,
      ],
      [
        'name' => 'Rajut Oversize',
        'slug' => str()->slug('46-rajut oversize'),
        'price' => 136500,
        'real_price' => 130000,
        'image' => 'item/Rajut Oversize.jpg',
        'category_id' => 3,
        'seller_id' => 20,
      ],
      [
        'name' => 'Kemeja Curdoroy Oversize',
        'slug' => str()->slug('46-kemeja curdoroy oversize'),
        'price' => 157500,
        'real_price' => 150000,
        'image' => 'item/Kemeja Curdoroy Oversize.jpg',
        'category_id' => 3,
        'seller_id' => 20,
      ],
      [
        'name' => 'Blouse Flower',
        'slug' => str()->slug('46-blouse flower'),
        'price' => 141750,
        'real_price' => 135000,
        'image' => 'item/Blouse Flower.jpg',
        'category_id' => 3,
        'seller_id' => 20,
      ],
      [
        'name' => 'Rok Bludru Plisket',
        'slug' => str()->slug('46-rok bludru plisket'),
        'price' => 84000,
        'real_price' => 80000,
        'image' => 'item/Rok Bludru Plisket.jpg',
        'category_id' => 3,
        'seller_id' => 20,
      ],
      [
        'name' => 'Kaftan Navy Payet',
        'slug' => str()->slug('46-kaftan navy payet'),
        'price' => 262500,
        'real_price' => 250000,
        'image' => 'item/Kaftan Navy Payet.jpg',
        'category_id' => 3,
        'seller_id' => 20,
      ],
      [
        'name' => 'Gamis Sage',
        'slug' => str()->slug('46-gamis sage'),
        'price' => 294000,
        'real_price' => 280000,
        'image' => 'item/Gamis Sage.jpg',
        'category_id' => 3,
        'seller_id' => 20,
      ],
      [
        'name' => 'Abaya Black Plisket',
        'slug' => str()->slug('46-abaya black plisket'),
        'price' => 367500,
        'real_price' => 350000,
        'image' => 'item/Abaya Black Plisket.jpg',
        'category_id' => 3,
        'seller_id' => 20,
      ],
      [
        'name' => 'Gamis Plisket Cerrutty',
        'slug' => str()->slug('46-gamis plisket cerrutty'),
        'price' => 294000,
        'real_price' => 280000,
        'image' => 'item/Gamis Plisket Cerrutty.jpg',
        'category_id' => 3,
        'seller_id' => 20,
      ],
      [
        'name' => 'Blouse Payet Premium',
        'slug' => str()->slug('46-blouse payet premium'),
        'price' => 178500,
        'real_price' => 170000,
        'image' => 'item/Blouse Payet Premium.jpg',
        'category_id' => 3,
        'seller_id' => 20,
      ],
      [
        'name' => 'Rok Jeans Span',
        'slug' => str()->slug('46-rok jeans span'),
        'price' => 141750,
        'real_price' => 135000,
        'image' => 'item/Rok Jeans Span.jpg',
        'category_id' => 3,
        'seller_id' => 20,
      ],
      [
        'name' => 'Rajut Crop',
        'slug' => str()->slug('46-rajut crop'),
        'price' => 126000,
        'real_price' => 120000,
        'image' => 'item/Rajut Crop.jpg',
        'category_id' => 3,
        'seller_id' => 20,
      ],
      [
        'name' => 'Kemeja Polos Linen',
        'slug' => str()->slug('46-kemeja polos linen'),
        'price' => 115500,
        'real_price' => 110000,
        'image' => 'item/Kemeja Polos Linen.jpg',
        'category_id' => 3,
        'seller_id' => 20,
      ],
      [
        'name' => 'Rajut Salur',
        'slug' => str()->slug('46-rajut salur'),
        'price' => 136500,
        'real_price' => 130000,
        'image' => 'item/Rajut Salur.jpg',
        'category_id' => 3,
        'seller_id' => 20,
      ],
      [
        'name' => 'Kemeja Crinkle',
        'slug' => str()->slug('46-kemeja crinkle'),
        'price' => 126000,
        'real_price' => 120000,
        'image' => 'item/Kemeja Crinkle.jpg',
        'category_id' => 3,
        'seller_id' => 20,
      ],
      [
        'name' => 'Outer Rajut',
        'slug' => str()->slug('46-outer rajut'),
        'price' => 157500,
        'real_price' => 150000,
        'image' => 'item/Outer Rajut.jpg',
        'category_id' => 3,
        'seller_id' => 20,
      ],
      [
        'name' => 'Kemeja Motif',
        'slug' => str()->slug('46-kemeja motif'),
        'price' => 131250,
        'real_price' => 125000,
        'image' => 'item/Kemeja Motif.jpg',
        'category_id' => 3,
        'seller_id' => 20,
      ],
      [
        'name' => 'Outer Crop',
        'slug' => str()->slug('46-outer crop'),
        'price' => 157500,
        'real_price' => 150000,
        'image' => 'item/Outer Crop.jpg',
        'category_id' => 3,
        'seller_id' => 20,
      ],
      [
        'name' => 'Rajut Knit',
        'slug' => str()->slug('46-rajut knit'),
        'price' => 173250,
        'real_price' => 165000,
        'image' => 'item/Rajut Knit.jpg',
        'category_id' => 3,
        'seller_id' => 20,
      ],
      [
        'name' => 'Outer Rajut Premium',
        'slug' => str()->slug('46-outer rajut premium'),
        'price' => 126000,
        'real_price' => 120000,
        'image' => 'item/Outer Rajut Premium.jpg',
        'category_id' => 3,
        'seller_id' => 20,
      ],
      [
        'name' => 'Outer Knit Plisket',
        'slug' => str()->slug('46-outer knit plisket'),
        'price' => 78750,
        'real_price' => 75000,
        'image' => 'item/Outer Knit Plisket.jpg',
        'category_id' => 3,
        'seller_id' => 20,
      ],
      [
        'name' => 'Blouse Payet',
        'slug' => str()->slug('46-blouse payet'),
        'price' => 141750,
        'real_price' => 135000,
        'image' => 'item/Blouse Payet.jpg',
        'category_id' => 3,
        'seller_id' => 20,
      ],
      [
        'name' => 'Blouse Shimmer',
        'slug' => str()->slug('46-blouse shimmer'),
        'price' => 157500,
        'real_price' => 150000,
        'image' => 'item/Blouse Shimmer.jpg',
        'category_id' => 3,
        'seller_id' => 20,
      ],
      [
        'name' => 'Blouse Flower Premium',
        'slug' => str()->slug('46-blouse flower premium'),
        'price' => 183750,
        'real_price' => 175000,
        'image' => 'item/Blouse Flower Premium.jpg',
        'category_id' => 3,
        'seller_id' => 20,
      ],
      [
        'name' => 'Ayy Blouse',
        'slug' => str()->slug('47-ayy blouse'),
        'price' => 126000,
        'real_price' => 120000,
        'image' => 'item/Ayy Blouse.jpg',
        'category_id' => 3,
        'seller_id' => 21,
      ],
      [
        'name' => 'Ayy Kaftan',
        'slug' => str()->slug('47-ayy kaftan'),
        'price' => 262500,
        'real_price' => 250000,
        'image' => 'item/Ayy Kaftan.jpg',
        'category_id' => 3,
        'seller_id' => 21,
      ],
      [
        'name' => 'Blezer Mini',
        'slug' => str()->slug('47-blezer mini'),
        'price' => 157500,
        'real_price' => 150000,
        'image' => 'item/Blezer Mini.jpg',
        'category_id' => 3,
        'seller_id' => 21,
      ],
      [
        'name' => 'Blouse Import Allsize',
        'slug' => str()->slug('47-blouse import allsize'),
        'price' => 115500,
        'real_price' => 110000,
        'image' => 'item/Blouse Import Allsize.jpg',
        'category_id' => 3,
        'seller_id' => 21,
      ],
      [
        'name' => 'Tunik Rajut BKK',
        'slug' => str()->slug('47-tunik rajut bkk'),
        'price' => 189000,
        'real_price' => 180000,
        'image' => 'item/Tunik Rajut BKK.jpg',
        'category_id' => 3,
        'seller_id' => 21,
      ],
      [
        'name' => 'Blouse Levis Import',
        'slug' => str()->slug('47-blouse levis import'),
        'price' => 147000,
        'real_price' => 140000,
        'image' => 'item/Blouse Levis Import.jpg',
        'category_id' => 3,
        'seller_id' => 21,
      ],
      [
        'name' => 'Crop Top Sweater',
        'slug' => str()->slug('47-crop top sweater'),
        'price' => 157500,
        'real_price' => 150000,
        'image' => 'item/Crop Top Sweater.jpg',
        'category_id' => 3,
        'seller_id' => 21,
      ],
      [
        'name' => 'Gamis Motif',
        'slug' => str()->slug('47-gamis motif'),
        'price' => 220500,
        'real_price' => 210000,
        'image' => 'item/Gamis Motif.jpg',
        'category_id' => 3,
        'seller_id' => 21,
      ],
      [
        'name' => 'Hoodie Elephant',
        'slug' => str()->slug('47-hoodie elephant'),
        'price' => 189000,
        'real_price' => 180000,
        'image' => 'item/Hoodie Elephant.jpg',
        'category_id' => 3,
        'seller_id' => 21,
      ],
      [
        'name' => 'Hoodie Polos',
        'slug' => str()->slug('47-hoodie polos'),
        'price' => 168000,
        'real_price' => 160000,
        'image' => 'item/Hoodie Polos.jpg',
        'category_id' => 3,
        'seller_id' => 21,
      ],
      [
        'name' => 'Jeans Import L',
        'slug' => str()->slug('47-jeans import l'),
        'price' => 231000,
        'real_price' => 220000,
        'image' => 'item/Jeans Import L.jpg',
        'category_id' => 3,
        'seller_id' => 21,
      ],
      [
        'name' => 'Kaftan Motif',
        'slug' => str()->slug('47-kaftan motif'),
        'price' => 294000,
        'real_price' => 280000,
        'image' => 'item/Kaftan Motif.jpg',
        'category_id' => 3,
        'seller_id' => 21,
      ],
      [
        'name' => 'Kaos Oversize',
        'slug' => str()->slug('47-kaos oversize'),
        'price' => 199500,
        'real_price' => 190000,
        'image' => 'item/Kaos Oversize.jpg',
        'category_id' => 3,
        'seller_id' => 21,
      ],
      [
        'name' => 'Kemeja Polos',
        'slug' => str()->slug('47-kemeja polos'),
        'price' => 147000,
        'real_price' => 140000,
        'image' => 'item/Kemeja Polos.jpg',
        'category_id' => 3,
        'seller_id' => 21,
      ],
      [
        'name' => 'Linean',
        'slug' => str()->slug('47-linean'),
        'price' => 157500,
        'real_price' => 150000,
        'image' => 'item/Linean.jpg',
        'category_id' => 3,
        'seller_id' => 21,
      ],
      [
        'name' => 'Azara Dress',
        'slug' => str()->slug('48-azara dress'),
        'price' => 262500,
        'real_price' => 250000,
        'image' => 'item/Azara Dress.jpeg',
        'category_id' => 3,
        'seller_id' => 22,
      ],
      [
        'name' => 'Blouse Organza',
        'slug' => str()->slug('48-blouse organza'),
        'price' => 204750,
        'real_price' => 195000,
        'image' => 'item/Blouse Organza.jpg',
        'category_id' => 3,
        'seller_id' => 22,
      ],
      [
        'name' => 'Cardigan Strip Import',
        'slug' => str()->slug('48-cardigan strip import'),
        'price' => 189000,
        'real_price' => 180000,
        'image' => 'item/Cardigan Strip Import.jpg',
        'category_id' => 3,
        'seller_id' => 22,
      ],
      [
        'name' => 'Kaftan',
        'slug' => str()->slug('48-kaftan'),
        'price' => 178500,
        'real_price' => 170000,
        'image' => 'item/Kaftan.jpg',
        'category_id' => 3,
        'seller_id' => 22,
      ],
      [
        'name' => 'Kamyla Mukenah',
        'slug' => str()->slug('48-kamyla mukenah'),
        'price' => 199500,
        'real_price' => 190000,
        'image' => 'item/Kamyla Mukenah.jpeg',
        'category_id' => 3,
        'seller_id' => 22,
      ],
      [
        'name' => 'Kemeja Polos Nevada',
        'slug' => str()->slug('48-kemeja polos nevada'),
        'price' => 189000,
        'real_price' => 180000,
        'image' => 'item/Kemeja Polos Nevada.jpg',
        'category_id' => 3,
        'seller_id' => 22,
      ],
      [
        'name' => 'Oneset Crickle',
        'slug' => str()->slug('48-oneset crickle'),
        'price' => 210000,
        'real_price' => 200000,
        'image' => 'item/Oneset Crickle.jpg',
        'category_id' => 3,
        'seller_id' => 22,
      ],
      [
        'name' => 'Oneset Flower',
        'slug' => str()->slug('48-oneset flower'),
        'price' => 204750,
        'real_price' => 195000,
        'image' => 'item/Oneset Flower.jpg',
        'category_id' => 3,
        'seller_id' => 22,
      ],
      [
        'name' => 'Pastel Kaftan',
        'slug' => str()->slug('48-pastel kaftan'),
        'price' => 189000,
        'real_price' => 180000,
        'image' => 'item/Pastel Kaftan.jpeg',
        'category_id' => 3,
        'seller_id' => 22,
      ],
      [
        'name' => 'Sweater G',
        'slug' => str()->slug('48-sweater g'),
        'price' => 178500,
        'real_price' => 170000,
        'image' => 'item/Sweater G.jpg',
        'category_id' => 3,
        'seller_id' => 22,
      ],
      [
        'name' => 'Bkk Shirt',
        'slug' => str()->slug('49-bkk shirt'),
        'price' => 231000,
        'real_price' => 220000,
        'image' => 'item/Bkk Shirt.jpg',
        'category_id' => 3,
        'seller_id' => 23,
      ],
      [
        'name' => 'Blouse Brukat',
        'slug' => str()->slug('49-blouse brukat'),
        'price' => 199500,
        'real_price' => 190000,
        'image' => 'item/Blouse Brukat.jpg',
        'category_id' => 3,
        'seller_id' => 23,
      ],
      [
        'name' => 'Blouse Serut',
        'slug' => str()->slug('49-blouse serut'),
        'price' => 189000,
        'real_price' => 180000,
        'image' => 'item/Blouse Serut.jpg',
        'category_id' => 3,
        'seller_id' => 23,
      ],
      [
        'name' => 'Denim Blouse',
        'slug' => str()->slug('49-denim blouse'),
        'price' => 189000,
        'real_price' => 180000,
        'image' => 'item/Denim Blouse.jpg',
        'category_id' => 3,
        'seller_id' => 23,
      ],
      [
        'name' => 'Lisa Shilk Set',
        'slug' => str()->slug('49-lisa shilk set'),
        'price' => 241500,
        'real_price' => 230000,
        'image' => 'item/Lisa Shilk Set.jpg',
        'category_id' => 3,
        'seller_id' => 23,
      ],
      [
        'name' => 'Midea Blouse',
        'slug' => str()->slug('49-midea blouse'),
        'price' => 199500,
        'real_price' => 190000,
        'image' => 'item/Midea Blouse.jpg',
        'category_id' => 3,
        'seller_id' => 23,
      ],
      [
        'name' => 'Nana Set Hijab',
        'slug' => str()->slug('49-nana set hijab'),
        'price' => 367500,
        'real_price' => 350000,
        'image' => 'item/Nana Set Hijab.jpg',
        'category_id' => 3,
        'seller_id' => 23,
      ],
      [
        'name' => 'Vest Import Bkk',
        'slug' => str()->slug('49-vest import bkk'),
        'price' => 199500,
        'real_price' => 190000,
        'image' => 'item/Vest Import Bkk.jpg',
        'category_id' => 3,
        'seller_id' => 23,
      ],
      [
        'name' => 'White Blouse',
        'slug' => str()->slug('49-white blouse'),
        'price' => 199500,
        'real_price' => 190000,
        'image' => 'item/White Blouse.jpg',
        'category_id' => 3,
        'seller_id' => 23,
      ],
      [
        'name' => 'Butter Dress',
        'slug' => str()->slug('49-butter dress'),
        'price' => 294000,
        'real_price' => 280000,
        'image' => 'item/Butter Dress.jpg',
        'category_id' => 3,
        'seller_id' => 23,
      ],
    ];

    Item::insert($dataItem);
  }
}
